---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: startpunkt
rules:
- apiGroups: ["", "extensions", "networking.k8s.io", "discovery.k8s.io"]
  resources: ["ingresses", "namespaces", "endpointslices", "routes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["hajimari.io"]
  resources: ["applications", "bookmarks"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["startpunkt.ullberg.us"]
  resources: ["applications", "bookmarks"]
  verbs: ["get", "list", "create", "update", "delete", "watch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: startpunkt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: startpunkt
subjects:
- kind: ServiceAccount
  name: startpunkt-sa
  namespace: startpunkt


